
image: Visual Studio 2017
clone_depth: 1



init:
    - git config --global core.autocrlf true


# version format
version: 1.0.{build}

environment:
  api_key:
    secure: sQiEJkrPYPmtFrfHZIRaA4mCs2ULEDlMNOY/6LJizeN2PHTq9yi8yZiVuILHIqif

# branches to build
branches:
  # whitelist
  only:
    - master

install:
  # by default, all script lines are interpreted as batch
  - git checkout master

build_script: 
   - ps: .\src\build\bl.ps1 -major 1 -buildCounter "$env:appveyor_build_number"


artifacts:

  # pushing all *.nupkg files in build directory recursively
  - path: '.\.build\ready\**\*.nupkg'


deploy_script:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
  - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package -ApiKey $env:api_key; if ($lastexitcode -ne 0) {throw}}


