
image: Visual Studio 2017
clone_depth: 10

# version format
version: 1.0.{build}
# branches to build
branches:
  # whitelist
  only:
    - master
    - production
build_script: 
   - ps: .\src\build\bl.ps1
