
image: Visual Studio 2017
clone_depth: 1



init:
    - git config --global core.autocrlf true


# version format
version: 1.0.{build}
# branches to build
branches:
  # whitelist
  only:
    - master

install:
  # by default, all script lines are interpreted as batch
  - git checkout master

build_script: 
   - ps: .\src\build\bl.ps1 .\src\build\bl.ps1 -major 1 -buildCounter {build}


artifacts:

  # pushing all *.nupkg files in build directory recursively
  - path: '.\.build\ready\**\*.nupkg'